FROM golang:1.16-alpine as Builder

WORKDIR /build

COPY main.go .
COPY go.mod .

RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM scratch

WORKDIR /app

COPY --from=Builder /build/app .

CMD ["./app"]
